"""
models/hospital_data.py
All hospital records, ambulance fleet, budget tier reference, and emergency log.
In a production system these would live in Firestore / MongoDB.
For hackathon: kept in-memory so the app runs instantly with zero setup.
"""

# ── HOSPITALS ─────────────────────────────────────────────────────────────────

HOSPITALS = [
    {
        "id": 1,
        "name": "AIIMS Jodhpur",
        "address": "E4, MIA Basni Phase-2, Opposite AIIMS Campus, Jodhpur - 342005",
        "lat": 26.248, "lng": 73.024,
        "phone": "+91-291-2740741",
        "type": "Government", "established": 2012,
        "accreditation": "NABH, NABL", "website": "aiims.edu/jodhpur",
        "total_beds": 720, "available_beds": 58,
        "icu_total": 120, "icu_available": 12,
        "trauma_total": 60, "trauma_available": 9,
        "burn_total": 30, "burn_available": 5,
        "equipment": {"Ventilator": True, "MRI Scanner": True, "CT Scanner": True, "Dialysis": True, "Cath Lab": True, "PET-CT": True, "Modular OT": True},
        "specialists": {"Cardiologist": True, "Neurosurgeon": True, "Orthopedic": True, "Burns Specialist": True, "Trauma Surgeon": True, "Oncologist": True, "Nephrologist": True},
        "rating": 4.8, "status": "Available", "ambulances": 10, "er_wait_min": 18,
        "budget_tier": "Low",
        "consultation_fee": 10, "emergency_fee": 100, "icu_per_day": 500,
        "surgery_range": "Free - 10,000",
        "about": "Premier AIIMS campus. First NABH-accredited AIIMS in India. 65 ICU beds, 8 modular OTs, cardiac cath lab. Handles 1,500+ OPD patients daily. Empanelled with CGHS, Railways, ESIC, Bhamashah.",
        "key_doctors": ["Dr. Pratap Sanchetee (Neurologist)", "Dr. Rahul Garg (Orthopedic)", "Dr. Ashish Solanki (Neonatologist)"],
        "services": ["Cardiology", "Neurosurgery", "Oncology", "Nephrology", "Orthopedics", "Gastroenterology", "Pulmonology", "Psychiatry", "Pediatrics", "Burns Unit", "Trauma Care", "Dialysis", "Blood Bank", "24hr Emergency", "Bone Marrow Transplant"],
    },
    {
        "id": 2,
        "name": "Dr. S.N. Medical College & MG Hospital (Umaid Hospital)",
        "address": "Umaid Hospital Road, Near Geeta Bhawan, Pratap Nagar, Jodhpur - 342003",
        "lat": 26.279, "lng": 73.008,
        "phone": "+91-291-2434374",
        "type": "Government", "established": 1945,
        "accreditation": "MCI Approved", "website": "",
        "total_beds": 1800, "available_beds": 145,
        "icu_total": 250, "icu_available": 24,
        "trauma_total": 100, "trauma_available": 16,
        "burn_total": 60, "burn_available": 8,
        "equipment": {"Ventilator": True, "MRI Scanner": True, "CT Scanner": True, "Dialysis": True, "Cath Lab": True, "PET-CT": False, "Modular OT": True},
        "specialists": {"Cardiologist": True, "Neurosurgeon": True, "Orthopedic": True, "Burns Specialist": True, "Trauma Surgeon": True, "Oncologist": True, "Nephrologist": True},
        "rating": 4.1, "status": "Available", "ambulances": 14, "er_wait_min": 25,
        "budget_tier": "Low",
        "consultation_fee": 10, "emergency_fee": 50, "icu_per_day": 300,
        "surgery_range": "Free - 5,000",
        "about": "Jodhpur's oldest and largest government hospital. Main SNMC campus includes Umaid Hospital, Maternity Hospital, Kamla Nehru Chest Hospital and specialty blocks. Free treatment for BPL and government scheme patients.",
        "key_doctors": ["Multiple Faculty Professors", "Senior Resident Specialists"],
        "services": ["Maternity", "Pediatrics", "General Surgery", "Orthopedics", "ENT", "Ophthalmology", "Cardiology", "Neurology", "Burns Unit", "Trauma", "Dialysis", "Blood Bank", "Psychiatry", "Skin & VD", "TB & Chest", "Radiology"],
    },
    {
        "id": 3,
        "name": "Medipulse Hospital",
        "address": "E4, MIA Basni Phase-2, Opposite AIIMS, Jodhpur - 342005",
        "lat": 26.252, "lng": 73.025,
        "phone": "+91-291-2740740",
        "type": "Private", "established": 2008,
        "accreditation": "NABH Accredited (First in Jodhpur)", "website": "medipulse.in",
        "total_beds": 300, "available_beds": 32,
        "icu_total": 65, "icu_available": 9,
        "trauma_total": 25, "trauma_available": 5,
        "burn_total": 12, "burn_available": 2,
        "equipment": {"Ventilator": True, "MRI Scanner": True, "CT Scanner": True, "Dialysis": True, "Cath Lab": True, "PET-CT": True, "Modular OT": True},
        "specialists": {"Cardiologist": True, "Neurosurgeon": True, "Orthopedic": True, "Burns Specialist": False, "Trauma Surgeon": True, "Oncologist": True, "Nephrologist": True},
        "rating": 4.7, "status": "Available", "ambulances": 8, "er_wait_min": 7,
        "budget_tier": "High",
        "consultation_fee": 700, "emergency_fee": 2500, "icu_per_day": 10000,
        "surgery_range": "20,000 - 3,00,000",
        "about": "Jodhpur's most trusted and first NABH-accredited private hospital. First TAVI procedure in Jodhpur. 8 modular OTs, 65 ICU/critical care beds, dedicated cardiac cath lab.",
        "key_doctors": ["Dr. Pratap Sanchetee (Neurologist)", "Dr. Rahul Garg (Orthopedic)", "Dr. Amit Singhvi (Urologist)", "Dr. S.N. Mathuriya (Neurosurgeon)", "Dr. Nagesh Vyas (Intensivist)"],
        "services": ["Cardiac Surgery", "Angioplasty", "Neurosurgery", "Joint Replacement", "Bariatric Surgery", "Oncology", "Nephrology", "Gastroenterology", "IVF", "NICU", "Robotic Surgery", "Laparoscopy", "24hr Emergency", "Trauma Care"],
    },
    {
        "id": 4,
        "name": "Goyal Hospital & Research Centre",
        "address": "961/3, Residency Road, Opp. Rotary Hall, Sardarpura, Jodhpur - 342003",
        "lat": 26.291, "lng": 73.032,
        "phone": "+91-291-2432144",
        "type": "Private", "established": 1989,
        "accreditation": "NABH Accredited", "website": "goyalhospital.com",
        "total_beds": 200, "available_beds": 28,
        "icu_total": 40, "icu_available": 7,
        "trauma_total": 18, "trauma_available": 4,
        "burn_total": 10, "burn_available": 2,
        "equipment": {"Ventilator": True, "MRI Scanner": True, "CT Scanner": True, "Dialysis": True, "Cath Lab": True, "PET-CT": False, "Modular OT": True},
        "specialists": {"Cardiologist": True, "Neurosurgeon": True, "Orthopedic": True, "Burns Specialist": False, "Trauma Surgeon": False, "Oncologist": True, "Nephrologist": True},
        "rating": 4.6, "status": "Available", "ambulances": 5, "er_wait_min": 8,
        "budget_tier": "High",
        "consultation_fee": 800, "emergency_fee": 2000, "icu_per_day": 9000,
        "surgery_range": "20,000 - 2,50,000",
        "about": "Founded in 1989 by Dr. Anand Goyal. Pioneer of advanced cardiac care in western Rajasthan — first dialysis unit, first ICCU, first cardiac catheterization lab, and first knee replacement in the region.",
        "key_doctors": ["Dr. Anand Goyal (Founder, Cardiologist)", "Senior Specialists across departments"],
        "services": ["Cardiac Surgery", "Angioplasty", "Bypass", "Cath Lab", "Dialysis", "Knee Replacement", "Hip Replacement", "Neurosurgery", "Oncology", "IVF", "Urology", "Eye Surgery", "Dental", "24hr Emergency"],
    },
    {
        "id": 5,
        "name": "Shri Ram Hospital (Pal Road)",
        "address": "In front of Hanuwant School, Pal Road, Jodhpur - 342001",
        "lat": 26.258, "lng": 73.038,
        "phone": "+91-291-2772111",
        "type": "Private", "established": 2005,
        "accreditation": "NABH Registered, ISO 9001", "website": "shriramhospitals.com",
        "total_beds": 150, "available_beds": 22,
        "icu_total": 30, "icu_available": 6,
        "trauma_total": 15, "trauma_available": 4,
        "burn_total": 8, "burn_available": 2,
        "equipment": {"Ventilator": True, "MRI Scanner": True, "CT Scanner": True, "Dialysis": True, "Cath Lab": False, "PET-CT": False, "Modular OT": True},
        "specialists": {"Cardiologist": True, "Neurosurgeon": False, "Orthopedic": True, "Burns Specialist": True, "Trauma Surgeon": True, "Oncologist": True, "Nephrologist": False},
        "rating": 4.5, "status": "Available", "ambulances": 5, "er_wait_min": 9,
        "budget_tier": "Medium",
        "consultation_fee": 500, "emergency_fee": 1500, "icu_per_day": 6000,
        "surgery_range": "15,000 - 1,50,000",
        "about": "One of western Rajasthan's fastest-growing multi-super-speciality hospitals. ISO 9001 and NABH registered. Internationally trained surgeons. Known for bariatrics, oncology, orthopaedics.",
        "key_doctors": ["Dr. Sunil Chandak (General Surgery, Laparoscopy)", "Dr. Om Prakash Choudhary (Orthopaedics)", "Dr. Vinay Vyas (Oncologist)"],
        "services": ["General Surgery", "Bariatric Surgery", "Oncology", "Urology", "Orthopedics", "ENT Head-Neck Oncology", "Plastic Surgery", "Laparoscopy", "IVF", "Cardiology", "Gynecology", "24hr Emergency"],
    },
    {
        "id": 6,
        "name": "Pacific Medical College & Hospital",
        "address": "Chittorgarh Road, Debari, Near Airport, Jodhpur - 342001",
        "lat": 26.312, "lng": 73.048,
        "phone": "+91-2953-270777",
        "type": "Private", "established": 2000,
        "accreditation": "NABH, NAAC A Grade", "website": "pacificmedicalcollege.com",
        "total_beds": 600, "available_beds": 80,
        "icu_total": 100, "icu_available": 18,
        "trauma_total": 45, "trauma_available": 10,
        "burn_total": 25, "burn_available": 5,
        "equipment": {"Ventilator": True, "MRI Scanner": True, "CT Scanner": True, "Dialysis": True, "Cath Lab": True, "PET-CT": False, "Modular OT": True},
        "specialists": {"Cardiologist": True, "Neurosurgeon": True, "Orthopedic": True, "Burns Specialist": True, "Trauma Surgeon": True, "Oncologist": True, "Nephrologist": True},
        "rating": 4.4, "status": "Available", "ambulances": 8, "er_wait_min": 12,
        "budget_tier": "Medium",
        "consultation_fee": 500, "emergency_fee": 1500, "icu_per_day": 6000,
        "surgery_range": "15,000 - 2,50,000",
        "about": "Large NABH & NAAC A-grade accredited teaching hospital. Multi-speciality campus. Handles 2000+ OPD patients daily.",
        "key_doctors": ["Senior Faculty & Specialists (Teaching Hospital)"],
        "services": ["Multi-Speciality Surgery", "Cardiac", "Neuro", "Ortho", "Transplant", "Oncology", "Gynecology", "NICU", "Burns", "Trauma", "Dialysis", "Blood Bank"],
    },
    {
        "id": 7,
        "name": "Shri Mahaveer Cancer Hospital & Research Centre",
        "address": "Jawahar Lal Nehru Road, Jodhpur - 342003",
        "lat": 26.276, "lng": 73.028,
        "phone": "+91-291-2655000",
        "type": "Private", "established": 1997,
        "accreditation": "NABH, NABL", "website": "mahaveercancerhospital.com",
        "total_beds": 200, "available_beds": 22,
        "icu_total": 40, "icu_available": 6,
        "trauma_total": 5, "trauma_available": 1,
        "burn_total": 3, "burn_available": 0,
        "equipment": {"Ventilator": True, "MRI Scanner": True, "CT Scanner": True, "Dialysis": True, "Cath Lab": False, "PET-CT": True, "Modular OT": True},
        "specialists": {"Cardiologist": False, "Neurosurgeon": False, "Orthopedic": False, "Burns Specialist": False, "Trauma Surgeon": False, "Oncologist": True, "Nephrologist": False},
        "rating": 4.7, "status": "Available", "ambulances": 3, "er_wait_min": 14,
        "budget_tier": "High",
        "consultation_fee": 800, "emergency_fee": 3000, "icu_per_day": 12000,
        "surgery_range": "40,000 - 5,00,000",
        "about": "Rajasthan's most trusted dedicated cancer centre. 5,000+ new cancer cases per year. Linear accelerator, PET-CT, bone marrow transplant. NABH and NABL accredited.",
        "key_doctors": ["Dr. Vinay Vyas (Medical Oncology)", "Senior Oncology Surgeons"],
        "services": ["Medical Oncology", "Surgical Oncology", "Radiation Therapy", "Chemotherapy", "Bone Marrow Transplant", "Palliative Care", "Cancer Screening", "Nuclear Medicine", "PET CT"],
    },
    {
        "id": 8,
        "name": "Kamla Nagar Hospital",
        "address": "Street No-5, Shyam Nagar, Pal Link Road, Jodhpur - 342008",
        "lat": 26.262, "lng": 73.046,
        "phone": "+91-291-2753466",
        "type": "Private", "established": 1990,
        "accreditation": "NABH Applied", "website": "knhospital.com",
        "total_beds": 120, "available_beds": 16,
        "icu_total": 22, "icu_available": 4,
        "trauma_total": 12, "trauma_available": 3,
        "burn_total": 6, "burn_available": 1,
        "equipment": {"Ventilator": True, "MRI Scanner": False, "CT Scanner": True, "Dialysis": True, "Cath Lab": False, "PET-CT": False, "Modular OT": False},
        "specialists": {"Cardiologist": False, "Neurosurgeon": False, "Orthopedic": True, "Burns Specialist": False, "Trauma Surgeon": False, "Oncologist": True, "Nephrologist": False},
        "rating": 4.3, "status": "Available", "ambulances": 3, "er_wait_min": 11,
        "budget_tier": "Medium",
        "consultation_fee": 400, "emergency_fee": 1200, "icu_per_day": 4500,
        "surgery_range": "10,000 - 1,00,000",
        "about": "Pioneer multi-speciality private hospital in Shyam Nagar. Known as one of Jodhpur's most trusted emergency and ICU centres. Strong in gynecology, pediatrics, oncology and general surgery.",
        "key_doctors": ["Dr. Ram Goel (General Surgery)", "Dr. Bina Goel (Gynecologist)", "Dr. Vinay Vyas (Oncologist)"],
        "services": ["General Surgery", "Gynecology", "Pediatrics", "Oncology", "Orthopedics", "ENT", "Ophthalmology", "Urology", "Physiotherapy", "24hr Emergency", "Dialysis"],
    },
    {
        "id": 9,
        "name": "Kailash Hospital Trauma & Research Centre",
        "address": "Pal Link Road, Jodhpur - 342008",
        "lat": 26.261, "lng": 73.048,
        "phone": "+91-291-2756500",
        "type": "Private", "established": 2006,
        "accreditation": "NABH Applied", "website": "",
        "total_beds": 100, "available_beds": 13,
        "icu_total": 20, "icu_available": 4,
        "trauma_total": 15, "trauma_available": 4,
        "burn_total": 8, "burn_available": 2,
        "equipment": {"Ventilator": True, "MRI Scanner": False, "CT Scanner": True, "Dialysis": True, "Cath Lab": False, "PET-CT": False, "Modular OT": True},
        "specialists": {"Cardiologist": False, "Neurosurgeon": False, "Orthopedic": True, "Burns Specialist": True, "Trauma Surgeon": True, "Oncologist": False, "Nephrologist": False},
        "rating": 4.2, "status": "Available", "ambulances": 3, "er_wait_min": 8,
        "budget_tier": "Medium",
        "consultation_fee": 400, "emergency_fee": 1500, "icu_per_day": 5000,
        "surgery_range": "10,000 - 1,00,000",
        "about": "Dedicated trauma and research centre near Pal Link Road. 24x7 trauma surgeons. Known for handling road accident cases efficiently. Burns unit available.",
        "key_doctors": ["Trauma Surgery Team", "Orthopaedic Specialists"],
        "services": ["Trauma Surgery", "Critical Care", "Burns Care", "Orthopedics", "Emergency Medicine", "ICU", "Dialysis", "Blood Bank", "24hr Emergency"],
    },
    {
        "id": 10,
        "name": "Bhandari Hospital & Research Centre",
        "address": "11th A Road, Sardarpura, Jodhpur - 342003",
        "lat": 26.310, "lng": 73.033,
        "phone": "+91-291-2617200",
        "type": "Private", "established": 1998,
        "accreditation": "NABH Accredited", "website": "",
        "total_beds": 150, "available_beds": 18,
        "icu_total": 25, "icu_available": 4,
        "trauma_total": 12, "trauma_available": 3,
        "burn_total": 5, "burn_available": 1,
        "equipment": {"Ventilator": True, "MRI Scanner": True, "CT Scanner": True, "Dialysis": False, "Cath Lab": True, "PET-CT": False, "Modular OT": True},
        "specialists": {"Cardiologist": True, "Neurosurgeon": True, "Orthopedic": True, "Burns Specialist": False, "Trauma Surgeon": False, "Oncologist": False, "Nephrologist": False},
        "rating": 4.4, "status": "Available", "ambulances": 3, "er_wait_min": 9,
        "budget_tier": "High",
        "consultation_fee": 700, "emergency_fee": 2000, "icu_per_day": 9000,
        "surgery_range": "18,000 - 2,50,000",
        "about": "NABH accredited multi-speciality hospital in Sardarpura. Known for neurosurgery, cardiac and cosmetic procedures. 25+ years serving western Rajasthan.",
        "key_doctors": ["Senior Neuro & Cardiac Specialists", "Cosmetic Surgery Team"],
        "services": ["Neurosurgery", "Cardiology", "Cath Lab", "Orthopedics", "Laparoscopy", "ENT Surgery", "Eye Surgery", "Dental", "Cosmetic Surgery", "IVF", "24hr Emergency"],
    },
]

# ── BUDGET TIERS ──────────────────────────────────────────────────────────────

BUDGET_TIERS = {
    "Low": {
        "label": "Low Budget / Government",
        "color": "#27AE60",
        "description": "Government and charitable hospitals with subsidised or free treatment. Ideal for patients with limited financial resources or covered under government schemes.",
        "consultation": "10 - 200",
        "emergency":    "50 - 700",
        "icu_per_day":  "200 - 3,000",
        "surgery":      "Free - 55,000",
    },
    "Medium": {
        "label": "Medium Budget",
        "color": "#F39C12",
        "description": "Mid-range private hospitals with good facilities at moderate cost. Suitable for most families. Accept most insurance and cashless schemes.",
        "consultation": "300 - 500",
        "emergency":    "900 - 1,500",
        "icu_per_day":  "3,800 - 6,000",
        "surgery":      "7,000 - 1,50,000",
    },
    "High": {
        "label": "Premium / Super-Speciality",
        "color": "#E74C3C",
        "description": "NABH-accredited top-tier private and super-speciality hospitals with advanced equipment, experienced specialists and premium facilities.",
        "consultation": "600 - 900",
        "emergency":    "2,000 - 3,000",
        "icu_per_day":  "8,000 - 12,000",
        "surgery":      "18,000 - 5,00,000",
    },
}

# ── AMBULANCE FLEET ───────────────────────────────────────────────────────────

AMBULANCES = [
    {"id": "AMB-001", "driver": "Ramesh Kumar", "lat": 26.295, "lng": 73.019, "status": "Available", "phone": "+91-9876543210"},
    {"id": "AMB-002", "driver": "Suresh Yadav",  "lat": 26.281, "lng": 73.028, "status": "On Duty",   "phone": "+91-9876543211"},
    {"id": "AMB-003", "driver": "Vijay Singh",   "lat": 26.308, "lng": 73.011, "status": "Available", "phone": "+91-9876543212"},
    {"id": "AMB-004", "driver": "Priya Sharma",  "lat": 26.265, "lng": 73.041, "status": "Available", "phone": "+91-9876543213"},
    {"id": "AMB-005", "driver": "Anil Meena",    "lat": 26.275, "lng": 73.035, "status": "Available", "phone": "+91-9876543214"},
]

# ── LIVE EMERGENCY LOG (in-memory, resets on restart) ─────────────────────────
# Replace with Firestore in production (see database/firebase/)
EMERGENCIES = []
